spring:
  application:
    name: @project.artifactId@
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin, RETAIN_LAST
      discovery:
        locator:
          lower-case-service-id: true
          url-expression: "'http://'+serviceId+'/api/v1'"
          predicates:
            0:
              name: Path
              args[pattern]: "'/api/v1/'+serviceId+'/**'"
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - PUT
              - POST
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "content-type"
              - "authorization"
            maxAge: 3600
      metrics:
        enabled: true
build:
  version: @project.version@
