apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: iszell/gateway:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: service-port
            - containerPort: 8081
              name: management-port
          livenessProbe:
            httpGet:
              port: management-port
              path: /actuator/info
            initialDelaySeconds: 300
            timeoutSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: gateway
  labels:
    app: gateway
spec:
  ports:
    - name: "service"
      port: 8080
      targetPort: 8080
    - name: "management"
      port: 8081
      targetPort: 8081
  selector:
    app: gateway
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  replicas: 1
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: iszell/authentication:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: service-port
            - containerPort: 8081
              name: management-port
          livenessProbe:
            httpGet:
              port: management-port
              path: /actuator/info
            initialDelaySeconds: 300
            timeoutSeconds: 10
---
kind: Service
apiVersion: v1
metadata:
  name: authentication
  labels:
    app: authentication
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: authentication
  type: ClusterIP
